-- Creates a hidden, unclaimed venue for testing the real venue-claim flow.
-- Safe to rerun: once claimed, the ownership fields are preserved.

insert into public.venues (
  id,
  slug,
  name,
  description,
  country,
  city,
  area,
  address,
  postcode,
  latitude,
  longitude,
  rating,
  price_from,
  price_level,
  indoor,
  outdoor,
  food,
  alcohol,
  open_late,
  vibes,
  images,
  opening_hours,
  website,
  instagram,
  phone,
  business_status,
  verification_status,
  last_verified_at,
  data_sources,
  source_notes,
  is_claimed,
  claimed_by,
  claimed_at,
  partner_tier,
  monetisation_status,
  monetisation_notes,
  featured_eligible,
  featured_blocked_reason,
  is_test,
  primary_category,
  secondary_categories
)
values (
  'nokta-claim-flow-test',
  'nokta-claim-flow-test',
  'Nokta Claim Flow Test',
  'Private test venue for walking through Nokta''s venue claim and approval flow.',
  'United Kingdom',
  'London',
  'Soho',
  '1 Claim Test Street, London',
  'W1T 1AA',
  51.5155,
  -0.1321,
  null,
  15,
  2,
  true,
  true,
  true,
  false,
  true,
  array['casual', 'groups', 'late-night'],
  array[]::text[],
  '[
    {"day":"Monday","open":"14:00","close":"00:00"},
    {"day":"Tuesday","open":"14:00","close":"00:00"},
    {"day":"Wednesday","open":"14:00","close":"00:00"},
    {"day":"Thursday","open":"14:00","close":"00:00"},
    {"day":"Friday","open":"14:00","close":"01:00"},
    {"day":"Saturday","open":"12:00","close":"01:00"},
    {"day":"Sunday","open":"12:00","close":"00:00"}
  ]'::jsonb,
  null,
  null,
  null,
  'open',
  'verified',
  now(),
  '{"testFixture":"claim-flow"}'::jsonb,
  'Hidden admin-only fixture. Do not use for real customer activity.',
  false,
  null,
  null,
  'none',
  'not-contacted',
  'Claim-flow walkthrough fixture.',
  false,
  'Test venue; not eligible for public placement.',
  true,
  'shisha_lounge',
  array['lounge', 'late_night']
)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  area = excluded.area,
  address = excluded.address,
  postcode = excluded.postcode,
  source_notes = excluded.source_notes,
  is_test = true,
  featured_eligible = false,
  featured_blocked_reason = excluded.featured_blocked_reason,
  updated_at = now();

select
  id,
  slug,
  name,
  is_test,
  is_claimed,
  claimed_by
from public.venues
where id = 'nokta-claim-flow-test';
