do $$
begin
  if not exists (
    select 1
    from information_schema.tables
    where table_schema = 'public'
    and table_name = 'booking_requests'
  ) then
    raise exception 'public.booking_requests does not exist. Run supabase/sprint-33-booking-requests.sql first.';
  end if;
end $$;

update public.venues
set
  is_claimed = false,
  claimed_by = null,
  claimed_at = null,
  updated_at = now()
where slug = 'table-11-hounslow';

delete from public.booking_requests
where venue_id = 'sheesha-test-lounge'
and customer_email like 'test.booking.%@example.com';

insert into public.booking_requests (
  venue_id,
  submitted_by,
  customer_name,
  customer_email,
  customer_phone,
  party_size,
  requested_date,
  requested_time,
  occasion,
  message,
  status,
  owner_response_message,
  proposed_date,
  proposed_time,
  proposed_message,
  accepted_at,
  declined_at,
  proposed_at,
  cancelled_at,
  owner_last_updated_by,
  owner_last_updated_at,
  source_surface
)
values
  (
    'sheesha-test-lounge',
    null,
    'Amir Calendar Test',
    'test.booking.amir@example.com',
    '+44 7700 910001',
    2,
    current_date,
    '18:30',
    'Date night',
    'Window table if possible.',
    'pending',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Maya Calendar Test',
    'test.booking.maya@example.com',
    '+44 7700 910002',
    6,
    current_date,
    '20:00',
    'Birthday',
    'Birthday table with space for cake.',
    'accepted',
    'Confirmed. See you at 8pm.',
    null,
    null,
    null,
    now() - interval '1 hour',
    null,
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '1 hour',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Leo Calendar Test',
    'test.booking.leo@example.com',
    null,
    4,
    current_date + 3,
    '19:30',
    'Football night',
    'Table near a screen.',
    'alternative_proposed',
    null,
    current_date + 3,
    '21:00',
    'We can do 9pm instead.',
    null,
    null,
    now() - interval '2 hours',
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '2 hours',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Nadia Calendar Test',
    'test.booking.nadia@example.com',
    '+44 7700 910004',
    10,
    current_date + 3,
    '20:15',
    'Group booking',
    'Large group, mixed food and shisha.',
    'pending',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Omar Calendar Test',
    'test.booking.omar@example.com',
    '+44 7700 910005',
    3,
    current_date + 3,
    '21:30',
    'General',
    null,
    'accepted',
    'Confirmed for 10pm.',
    null,
    null,
    null,
    now() - interval '1 day',
    null,
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '1 day',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Sara Calendar Test',
    'test.booking.sara@example.com',
    '+44 7700 910006',
    8,
    current_date + 3,
    '23:00',
    'Private hire',
    'Testing next week density.',
    'pending',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Zain Calendar Test',
    'test.booking.zain@example.com',
    null,
    5,
    current_date + 10,
    '19:00',
    'Birthday',
    null,
    'declined',
    'Sorry, we are fully booked then.',
    null,
    null,
    null,
    null,
    now() - interval '3 days',
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '3 days',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Hana Calendar Test',
    'test.booking.hana@example.com',
    '+44 7700 910008',
    12,
    current_date + 14,
    '21:00',
    'Group booking',
    'Two-week future accepted booking.',
    'accepted',
    'Confirmed.',
    null,
    null,
    null,
    now() - interval '2 days',
    null,
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '2 days',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Noah Calendar Test',
    'test.booking.noah@example.com',
    null,
    2,
    current_date - 1,
    '18:00',
    'General',
    'Past completed booking for status testing.',
    'completed',
    'Completed.',
    null,
    null,
    null,
    now() - interval '2 days',
    null,
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '12 hours',
    'venue_page'
  ),
  (
    'sheesha-test-lounge',
    null,
    'Yasmin Calendar Test',
    'test.booking.yasmin@example.com',
    '+44 7700 910010',
    4,
    current_date - 2,
    '20:15',
    'General',
    'Past no-show booking for colour testing.',
    'no_show',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    (select id from auth.users where lower(email) = 'tufanbutuner@gmail.com' limit 1),
    now() - interval '1 day',
    'venue_page'
  );

notify pgrst, 'reload schema';
